name: Release Drafter

on:
  push:
    branches:
      - main
      - master
  pull_request_target:
    types: [opened, reopened, synchronize, edited]
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          name: next
          tag: next
          version: next
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT_QORNEA_TOKEN }}
